permalink: /:year-:month-:day-:title
markdown: kramdown
paginate: 10
encoding: utf-8

author:
  name: 吕立青
  email: jimmy.jinglv@gmail.com
  link: https://blog.jimmylv.info
  github: https://github.com/JimmyLv
  weibo: http://weibo.com/liqing215
  zhihu: http://www.zhihu.com/people/JimmyLv

project:
  title: NoBackend Website
  subtitle: 最美博客
  description: A powerful rich interactive web application by using nobackend tech stack.
  repository: https://github.com/JimmyLv/nobackend.website
  website: https://nobackend.website

# github endpoint
github:
  user: linesh-simplicity
  repo: linesh-simplicity.github.io
  branch: master
  posts: _posts
  subfolder: false

# api endpoint
api:
  github:
#    base: https://blog.jimmylv.info
    index: /api/index.json
    slides: /slides
    rss: /pages/atom.xml
  service:
    music:
      endpoint: http://app.atime.me/music-api-server
      provider: netease # or xiami
    zhihu:
      endpoint: http://api.kanzhihu.com
      userId: JimmyLv
    yql:
      endpoint: https://query.yahooapis.com/v1/public/yql

# active items for show
meta:
  songlist: 389445274 # 372072817 # 309097660
  active: 翻译
  tags:
    - 七牛
    - markdown

# chinese localization
locals:
  zhihu: 知乎
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# google analytics
ga:
  id: UA-75024401-1
  url: //nobackend.website

# disqus setting
disqus:
  disqus_shortname: nobackend-website
  disqus_identifier: nobackend-website

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - .idea/
  - node_modules
  - demo

include:
  - _config.yml
  - _ng
  - _vue
  - _react